### ISSUE TITLE
feat: can this tool help export new code issues list?

### ISSUE THREAD

**Issue by luisxiaomai** [cnescatlab/sonar-cnes-report#140]
### Expected behavior
Use this tool to export new code issues of one specified project ?

**Comment by Sancretor** [comment]
Hi @luisxiaomai 

Sorry for the delay...
I'm not sure to fully understand what you mean.
Did you mean that you would like the report to contain data on the new code like "New vulnerabilities" or "New debt" ?

**Comment by begarco** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.

Regards.
