### ISSUE TITLE
[ERROR] Impossible to reach SonarQube instance. 

### ISSUE THREAD

**Issue by tajraji** [cnescatlab/sonar-cnes-report#143]
### Expected behavior
able to access and produce sonar report
### Actual behavior
Throwing error
### Steps to reproduce behavior
Connect wtih sonar secure enterprise server using token using standalone method

**Comment by Sancretor** [comment]
Hi @tajraji 

Without any information we can't help you much.
We expect at least some logs, SonarQube version or if you use it standalone or as a plugin.

**Comment by Sancretor** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.

Regards.
