### ISSUE TITLE
Documentation: Sample CSV and Sample Excel file

### ISSUE THREAD

**Issue by maulik-modi** [cnescatlab/sonar-cnes-report#144]
Please share Sample CSV and Sample Excel file to get an idea of generated output to help understanding business value before setting up Plugin

**Comment by Sancretor** [comment]
Hi @maulik-modi 

You can download the report templates to have a general idea of what will be inside : https://github.com/lequal/sonar-cnes-report/tree/master/src/main/resources/template 
Or better, just download the standalone tool and try it with on your SonarQube data !

**Comment by begarco** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.

Regards.
