### ISSUE TITLE
[ERROR-SonarQube version: 8.5.0] Value of parameter 'facets' (fileUuids) must be one of..

### ISSUE THREAD

**Issue by syedabsar** [cnescatlab/sonar-cnes-report#172]
#### Describe the bug

Not able to run this on SonarQube 8.5.0, here's the output:

SonarQube online: true
Detected SonarQube version: 8.5.0
[ERROR] Value of parameter 'facets' (fileUuids) must be one of: [projects, moduleUuids, files, assigned_to_me, severities, statuses, resolutions, rules, assignees, authors, author, directories, scopes, languages, tags, types, owaspTop10, sansTop25, cwe, createdAt, sonarsourceSecurity]

#### User environment 

* OS: Centos 8

**Comment by Sancretor** [comment]
Hi @syedabsar 
Thanks for the feedback !
Unfortunately, we are not compatible with this SonarQube version for the moment.
Please have a look at the compatibility matrix in the README.

**Comment by jeritiana** [comment]
I had this issue too after upgrading to SQ 8.5.1.

FYI, here is the change I made to get my reports back (not intensively tested though):
```diff
--- src/main/resources/requests.properties.orig
+++ src/main/resources/requests.properties
@@ -44,7 +44,7 @@
 # Request to get the list of projects linked to a profile in SQ 5.X
 GET_PROJECT_QUALITY_PROFILES_REQUEST = %s/api/qualityprofiles/search?projectKey=%s
 # Request to get the list of issues linked to a project
-GET_ISSUES_REQUEST = %s/api/issues/search?projects=%s&facets=types,rules,severities,directories,fileUuids,tags&ps=%d&p=%d&additionalFields=rules,comments&resolved=%s&branch=%s
+GET_ISSUES_REQUEST = %s/api/issues/search?projects=%s&facets=types,rules,severities,directories,files,tags&ps=%d&p=%d&additionalFields=rules,comments&resolved=%s&branch=%s
 # Request to get the list of a project's facets
 GET_FACETS_REQUEST = %s/api/issues/search?projects=%s&resolved=false&facets=rules,severities,types&ps=1&p=1&branch=%s
 # Request to get the list of a project's facets
```

**Comment by gvuspace** [comment]
> Hi @syedabsar
> Thanks for the feedback !
> Unfortunately, we are not compatible with this SonarQube version for the moment.
> Please have a look at the compatibility matrix in the README.

Hi @Sancretor,

Do you have any roadmap on this?

For those of us who use a post-7.9 SonarQube version, the only way to remain supported by SonarSource and get the latest bugfixes and improvements is to track the latest version, at least until we reach the next LTS. It is therefore rather uncomfortable to keep using a non-latest intermediate version, which is why this issue is gaining significant interest.

**Comment by Sancretor** [comment]
Hi @gvuspace 

I totally agree, this situation is rather uncomfortable.  
Due to the lack of available time to work on this project, our initial plans were to only be compatible with LTS versions.  
Now, to be fully compatible with SonarQube 8.5 or 8.6, we would have to rewrite some key features inside the plugin, which would be painful because we also want to support 7.9.  

We could include this particular fix inside a new small release, but some features won't still work properly... so that would be half a solution...  
We will probably have someone working on 8.x full compatibility before the LTS release, but I can't make any promises on when this would be available.
We apologize for the inconvenience.

**Comment by gvuspace** [comment]
> Hi @gvuspace
> 
> I totally agree, this situation is rather uncomfortable.
> Due to the lack of available time to work on this project, our initial plans were to only be compatible with LTS versions.

I can understand that :)

> Now, to be fully compatible with SonarQube 8.5 or 8.6, we would have to rewrite some key features inside the plugin, which would be painful because we also want to support 7.9.

That's what I figured. The thing is, once the 8.X LTS is actually released, the plugin internals will most likely have to be rewritten and maintained anyway, so the issue will have to be addressed at some point. That being said, waiting for the API to stabilize is probably more efficient.

In the meantime, we can make do with the workaround mentioned above. It would just be nice if we could count on the plugin supporting the next LTS at some point.

**Comment by Sancretor** [comment]
@gvuspace Being fully compatible with the 8.x LTS "as soon as possible", that's our plan I promise !

**Comment by itbsg** [comment]
Dear @jeritiana

thank you for the small fix. We tried it and it worked fine. 

> I had this issue too after upgrading to SQ 8.5.1.
> 
> FYI, here is the change I made to get my reports back (not intensively tested though):
> 
> ```diff
> --- src/main/resources/requests.properties.orig
> +++ src/main/resources/requests.properties
> @@ -44,7 +44,7 @@
>  # Request to get the list of projects linked to a profile in SQ 5.X
>  GET_PROJECT_QUALITY_PROFILES_REQUEST = %s/api/qualityprofiles/search?projectKey=%s
>  # Request to get the list of issues linked to a project
> -GET_ISSUES_REQUEST = %s/api/issues/search?projects=%s&facets=types,rules,severities,directories,fileUuids,tags&ps=%d&p=%d&additionalFields=rules,comments&resolved=%s&branch=%s
> +GET_ISSUES_REQUEST = %s/api/issues/search?projects=%s&facets=types,rules,severities,directories,files,tags&ps=%d&p=%d&additionalFields=rules,comments&resolved=%s&branch=%s
>  # Request to get the list of a project's facets
>  GET_FACETS_REQUEST = %s/api/issues/search?projects=%s&resolved=false&facets=rules,severities,types&ps=1&p=1&branch=%s
>  # Request to get the list of a project's facets
> ```

Since this fix is not released yet, some might need to clone this project and build it theirself. In order to skip this necessity, we saved a patched file like the on you mentioned (within a subfolder, i.e., `sonar-cnes-report-3.3.1-patch/requests.properties`) and **prepended this patched file within the command classpath** like this:
```
java -cp ./sonar-cnes-report-3.3.1-patch:sonar-cnes-report-3.3.1.jar fr.cnes.sonar.report.ReportCommandLine ...
```

In result, the fixed property file is found first and the origin 3.3.1 release of Sonar CNES Report can be used without any further adaptation.

**Comment by Sancretor** [comment]
Hi all,

Just to give you an update on this topic.
The fix is merged inside the dev branch, as we're working on a new major release with compatibility on SonarQube 8.9 LTS.
So if you can't wait, you could build the dev branch to have a Work In Progress version.
Please be aware, some things might not work yet though ...

**Comment by Anon-Exploiter** [comment]
Looking forward to the release, got the same error as described in the issue! :))
