### ISSUE TITLE
{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

### ISSUE THREAD

**Issue by mayar-selim** [cnescatlab/sonar-cnes-report#195]
Hi,

I have the same error "{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}" with Sonarqube version 8.6.0 community edition and I have tried to update the base URL with http://URL and once again with https://URL according to issue#189 and the same issue is persisting . Can you help as it's a blocker to me.

**Comment by begarco** [comment]
Thanks for using the cnesreport.

CATLab community does not support unstable SonarQube version because they should not be deployed in production. The community put effort on maintaining cnesreport for LTS versions of SonarQube.

Your issue will be closed and we advise you to use the latest LTS version of SonarQube.

However, if you really need our plugin to work with an unstable version feel free to contribute through a pull request.

Regards.
