### ISSUE TITLE
How to enhance the reports with test metrics ?

### ISSUE THREAD

**Issue by rebse** [cnescatlab/sonar-cnes-report#291]
i would like to extend the reports with test metrics = unit tests (number, errors, failures, skipped, success) , code coverage
Is that possible ?

**Comment by Sancretor** [comment]
Hi @rebse 

Right now, we only show the total test coverage of the project.
I guess we could easily add the data you mentionned (number, errors, success, skipped, etc.), but it will require the development of a new feature.

I can change this issue to be an enhancement for the future release if you'd like.
But I can't make any promise regarding when we'd be able to implement it.
What do you think ?

**Comment by rebse** [comment]
Thanks for adding the enhancement label to this issue.
Until now i only implemented a bunch of custom Java rules, but have no experience with other plugins.
Would be great if you could give me some hints to get me going and i would be happy to participate
with a pull request.

**Comment by Sancretor** [comment]
Hi @rebse 
Sorry for the huge delay again...
I don't know if you already took a look into the codebase but here are some information to start with.

This enhancement will only impact the "report" folder inside the sources, the plugin part should remain unchanged.
The "providers" folder contains all classes which retrieve data from SonarQube server.
The "model" may be self explanatory, with classes handling the retrieved data.
The "exporters" folder is ... mostly a huge mess :) But here are classes used to replace placeholders inside the report templates with the retrieved data.
You may have a look at what already exists in "providers" & "model" to add some dedicated classes fort tests data.
In "exporters", you may have a look at "docx/DocXExporter.java" in order to call the dedicated methods to add data inside the report.

**Comment by Sancretor** [comment]
Hi @rebse 
Just to let you know that the feature is now implemented and merged in dev branch.
A couple more features/bugs are still to be merged before we could release the new version.
Hopefully, it will be very soon !

**Comment by rebse** [comment]
Hi @Sancretor :-)
great news!
And sorry, completely missed your mail 16 days ago :-(
due to stress from log4shell aftershocks ..

Gilbert

**Comment by Sancretor** [comment]
No worries !
I usually take weeks or months to answer here so ... :)
