### ISSUE TITLE
when will be support for v10.1.0.73491

### ISSUE THREAD

**Issue by johnfelipe** [cnescatlab/sonar-cnes-report#361]
Is important create this perfect reporting plugin for v10.x
is possible view a roadmap or kanban for this
tnks

**Comment by johnfelipe** [comment]
Anyone?

**Comment by johnfelipe** [comment]
anyone?

**Comment by ThalianSvk** [comment]
Hello, my colleague Petr Mach and I have updated the compatibility with version sonarqube 10.x. It is necessary to modify pom.xml, api.js, AbstractDataProvider.java and AbstractQualityGateProvider.java.  I am attaching the updated files in a zip folder.
[sonar-cnes-report-updated-files.zip](https://github.com/cnescatlab/sonar-cnes-report/files/12834886/sonar-cnes-report-updated-files.zip)

**Comment by johnfelipe** [comment]
Is only replace in root path that files?

**Comment by buzz3791** [comment]
@johnfelipe I successfully generated a cnes report using SonarQube 10.2.1 build 78527 on Windows Server using Almas pull request "Added version 10.x support" https://github.com/cnescatlab/sonar-cnes-report/pull/368.

I did have to tweak the commit done by @Sancretor to set the `com.google.protobuf:protobuf-java` dependency version to `3.22.2`.  Trying to run with the version `4.0.0-rc-2` merged with https://github.com/cnescatlab/sonar-cnes-report/commit/2089d7837629b7d0a0260f031e2adc197c6f677f caused an "HTTP Status 500 Internal Server Error" which is due to this error in web.log
```
javax.servlet.ServletException: 'boolean com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(com.google.protobuf.CodedInputStream, com.google.protobuf.ExtensionRegistryLite, int)'
```
The exact version of cnesreport I built from is:
```
PS C:\dev\sqreport\sonar-cnes-report> git branch -vv
* almas/master 1ab6a25 #365 It's just related files lint fixes.
  master       f7ab23b [origin/master] Merge pull request #353 from tcsabina/master
PS C:\dev\sqreport\sonar-cnes-report> 
```
which produced `cnesreport-4.2.1.jar`

**Comment by Topin2001** [comment]
Hello, thanks for the interest, however, we only support the LTS version, which is currently not available for the v10.
