### ISSUE TITLE
Label translation fails

### ISSUE THREAD

**Issue by kaefferlein** [cnescatlab/sonar-cnes-report#363]
#### Describe the bug

When using  Sonarqube helm chart of the version 10.1.0 https://github.com/SonarSource/helm-chart-sonarqube/releases/tag/sonarqube-10.1.0-sonarqube-dce-10.1.0 some labels are not displayed correctly with the version `4.1.2` of this plugin.

#### To reproduce

> _Steps to reproduce the behavior._

1. Go to a project and check the overview page
2. See error where e.g. `Coverage` is displayed as `overview.measurement_type.COVERAGE`

#### Expected behavior

Translation should work and correct values are displayed (not their keys).

#### Screenshots & log
<img width="904" alt="image" src="https://github.com/cnescatlab/sonar-cnes-report/assets/38203192/c70b3aa1-0dc6-46a4-b05a-4f46c4b92ad8">

**Comment by Topin2001** [comment]
Since you're using sonarqube v10 and we are still supporting only sonarqube v9.9 LTS, this behavior is not unexpected. In order to fix this I can only advise you to use sonarqube 9.9 LTS. Otherwise, feel free to open a merge request with a fix, since I'm starting to look into the update for sonarqube 10, help is welcome
