### ISSUE TITLE
An error has occurred. Please contact your administrator

### ISSUE THREAD

**Issue by KAILASH08** [cnescatlab/sonar-cnes-report#383]
#### Describe the bug

> While trying to generate a report using CNES report it gives error, {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

#### To reproduce

> _Steps to reproduce the behavior._

1. Go to 'More and select CNES Report'
2. Click on 'Generate button to generate report'
3. See error "{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}"

#### Expected behavior

> It should generate the report._

#### Screenshots & log

> Attached

#### User environment 

> _Please complete the following information._
http://localhost:8080/extension/cnesreport/report
* OS: [e.g. Windows 11]
*sonar-cnes-report-3.2.2.jar
* 
<img width="769" alt="image" src="https://github.com/cnescatlab/sonar-cnes-report/assets/13345005/8ac1e2b7-4c8b-4328-9287-f050490e9e69">
sonarqube-7.9.6

**Comment by Topin2001** [comment]
Unfortunately, the issue seems to be from your side since I'm not able to reproduce it. However, I can recommend you to upgrade at least the sonar-cnes-report version that you're using. It might help. Feel free to reopen a ticket if you get new error/log that can help us to resolve the problem if it comes with the plugin itself.
