### ISSUE TITLE
WARN: Plugin SonarQube CNES Report [cnesreport] uses a child first classloader which is deprecated

### ISSUE THREAD

**Issue by 2Fey** [cnescatlab/sonar-cnes-report#92]
Hi team! Thx for your project!
We use your plugin with sonar and jenkins. Can you explain one warning?
`WARN: Plugin SonarQube CNES Report [cnesreport] uses a child first classloader which is deprecated`
Our security team is annoyed by every warnings...

**Comment by begarco** [comment]
Hi @2Fey,

Because of the upgrade of java version, we encountered some issues with jaxb dependency. We've tried many solution and we've try to fix it with the line below in the [pom.xml](/lequal/sonar-cnes-report/blob/master/pom.xml).
```xml
<sonar.useChildFirstClassLoader>true</sonar.useChildFirstClassLoader>
```
Nethertheless, I'm not sure this is necessary in the current version.

This line may be removed but it has to be tested.
